# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7FPbOfq2dCaoiKmkparIUSZINKbD1p8
"""

# app.py

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -------------------------
# Page Config
# -------------------------
st.set_page_config(
    page_title="Scene Classification",
    page_icon="🌍",
    layout="centered"
)

# -------------------------
# Header
# -------------------------
st.markdown(
    """
    <h1 style='text-align:center;color:#1E88E5;'>
        🌍 Scene Image Classification
    </h1>
    <p style='text-align:center;font-size:18px;'>
        Upload an image and identify whether it is a
        Mountain, Sea, Street, Forest, Building, or Glacier.
    </p>
    """,
    unsafe_allow_html=True
)

# -------------------------
# Load Model
# -------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("scene_classifier.h5")

model = load_model()

# Class Names
classes = [
    "Building",
    "Forest",
    "Glacier",
    "Mountain",
    "Sea",
    "Street"
]

# -------------------------
# Image Preprocessing
# -------------------------
def preprocess_image(img):
    img = img.resize((150, 150))
    img_array = np.array(img)

    if img_array.shape[-1] == 4:
        img_array = img_array[:, :, :3]

    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    return img_array

# -------------------------
# Upload Section
# -------------------------
uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

    if st.button("Classify Image"):

        with st.spinner("Analyzing image..."):

            processed_image = preprocess_image(image)

            prediction = model.predict(processed_image)

            predicted_class = classes[np.argmax(prediction)]
            confidence = np.max(prediction) * 100

        st.success("Prediction Complete!")

        st.markdown(
            f"""
            ### Result
            **Category:** {predicted_class}

            **Confidence:** {confidence:.2f}%
            """
        )

        st.progress(int(confidence))

# -------------------------
# Footer
# -------------------------
st.markdown("---")
st.markdown(
    "<p style='text-align:center;'>Built with Streamlit & TensorFlow</p>",
    unsafe_allow_html=True
)